platform :ios, '7.0'

pod 'NUI', '0.5.4'
pod 'Masonry', '0.4.0'
pod 'UIView+AutoLayout', '1.3.0'
pod 'RegexKitLite', '4.0'
pod 'JSONKit', '~> 1.4'
pod 'libextobjc', '0.4'
pod 'ReactiveCocoa', git: 'git@github.com:Sellegit/ReactiveCocoa.git', branch: 'stable'
pod 'ReactiveViewModel', '0.2'
