TextField#primaryTextField.textField(text=syncValue)
TextField#secondaryTextField.textField(text=syncValue)
Label#displayLabel.displayLabel(text=syncValue)
TextField#primaryTextField2.textField(text=syncValue2)
TextField#secondaryTextField2.textField(text=syncValue2)
Label#displayLabel2.displayLabel(text=syncValue2)
